### ISSUE TITLE
GitHub pages support?

### ISSUE THREAD

**Issue by devth** [paulrobertlloyd/jekyll-pypedown#2]
Is this intended to work with GitHub pages? I get build errors from GitHub when using it, even though it works locally on my machine.

**Comment by paulrobertlloyd** [comment]
Hi @devth. Unfortunately, GitHub pages only supports a limited number of plugins. See their docs for details: https://help.github.com/articles/using-jekyll-plugins-with-github-pages/

**Comment by devth** [comment]
Got it. Thanks.
